spring.application.name=hotel-booking
spring.datasource.url=jdbc:postgresql://ep-holy-band-a10fc13x-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_68LVINenwzEH
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.security.jwt.secret-key=TranNhatNamHocVienCongNgheBuuChinhVienThong
spring.application.security.jwt.access-token=60000000
spring.application.security.jwt.refresh-token=360000000